python train.py \
  --task nc \
  --dataset disease_nc \
  --normalize-feats 1 \
  --seed 1234 \
  --num_runs 10 \
  --epochs 1000 \
  --step_lr_reduce_freq 5000 \
  --patience 300  \
  --eucl_lr 0.01 \
  --stie_lr 0.01 \
  --dim 64 \
  --num-layers 10 \
  --num_centroid 200 \
  --skip-connections True \
  --log-freq 40 \
  --log-to-stdout False