python train.py \
  --task nc \
  --dataset disease_nc \
  --seed 1234 \
  --num_runs 10 \
  --epochs 1000 \
  --step_lr_reduce_freq 5000 \
  --eucl_lr 0.01 \
  --stie_lr 0.01 \
  --dim 64 \
  --num-layers 5 \
  --num_centroid 200 \
  --skip_connections True \
  --log-freq 40 \
  --log-to-stdout False \
  --ema 0.99